### ISSUE TITLE
Bug while clicking in the Mass Summary / Mode Table (without modes)

### ISSUE THREAD

**Issue by shapelessguy** [virtualsatellite/VirtualSatellite4-CEF#184]
Get a look to this console error message:

MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
        at de.dlr.sc.virsat.model.dvlm.structural.util.StructuralElementInstanceHelper.getRoot(StructuralElementInstanceHelper.java:49)
        at de.dlr.sc.virsat.model.extension.cefx.util.CefModeHelper.getAllModes(CefModeHelper.java:47)
        at de.dlr.sc.virsat.model.extension.cefx.util.CefModeHelper.getModeByName(CefModeHelper.java:166)
        at de.dlr.sc.virsat.model.extension.cefx.ui.modesview.ModeTableView$ColumnSelectionListener.widgetSelected(ModeTableView.java:338)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by dellerDLR** [comment]
Hey @shapelessguy 
thank you for reporting this bug. Can you give more us more information how we can reproduce the bug?
